WepApp2.2/Models/CalculatorViewModel.cs
namespace WebApp2._2.Models
{
    public class CalculatorViewModel
    {
        public int X { get; set; }
        public int Y { get; set; }
        public string Action { get; set; }
        public string Calc() 
        {
            return Action switch
            {
                "+" => $"{X} + {Y} = {X + Y}",
                "-" => $"{X} - {Y} = {X - Y}",
                "*" => $"{X} * {Y} = {X * Y}",
                "/" when Y != 0 => $"{X} / {Y} = {X / Y}",
                "/" when Y == 0 => "Error: division by zero",
                _ => "Invalid operation"
            };
        }
    }
}

WepApp2.2/Models/ErrorViewModel.cs
namespace WebApp2._2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WepApp2.2/Controllers/CalcController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp2._2.Models;


namespace WebApp2._2.Controllers
{
    public class CalcController : Controller
    {
        private Random _random { get; set; } = new Random();

        private readonly ILogger<CalcController> _logger;

        public CalcController(ILogger<CalcController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ActionName("Manual")]
        public IActionResult ManualParsingSingle()
        {
            if (Request.Method == "POST")
            {
                try
                {
                    var calc = new CalculatorViewModel()
                    {
                        X = Int32.Parse(HttpContext.Request.Form["x"]),
                        Action = HttpContext.Request.Form["action"],
                        Y = Int32.Parse(HttpContext.Request.Form["y"])
                    };
                    ViewBag.Result = calc.Calc();
                }
                catch
                {
                    ViewBag.Result = "Invalid input";
                }
                return View("Result");
            }
            return View("Manual");
        }

        //-----------------------------------------

        [HttpGet]
        [ActionName("ManualWithParsingSeparate")]
        public IActionResult ManualWithParsingSeparateGet()
        {
            return View("Manual");
        }
        [HttpPost]
        [ActionName("ManualWithParsingSeparate")]
        public IActionResult ManualWithParsingSeparatePost()
        {
            try
            {
                var calc = new CalculatorViewModel()
                {
                    X = Int32.Parse(HttpContext.Request.Form["x"]),
                    Action = HttpContext.Request.Form["action"],
                    Y = Int32.Parse(HttpContext.Request.Form["y"])
                };
                ViewBag.Result = calc.Calc();
            }
            catch
            {
                ViewBag.Result = "Invalid input";
            }
            return View("Result");
        }

        //-----------------------------------------

        [HttpGet]
        [ActionName("ModelBindingInParameters")]
        public IActionResult ModelBindingParametersGet()
        {
            return View("Manual");
        }

        [HttpPost]
        [ActionName("ModelBindingInParameters")]
        public IActionResult ModelBindingParametersPost(int x, string action, int y)
        {
            if (ModelState.IsValid)
            {
                var calc = new CalculatorViewModel
                {
                    X = x,
                    Y = y,
                    Action = action
                };
                ViewBag.Result = calc.Calc();
            }
            else
            {
                ViewBag.Result = "Invalid input";
            }
            return View("Result");
        }

        //-----------------------------------------

        [HttpGet]
        [ActionName("ModelBindingInSeparateModels")]
        public IActionResult ModelBindingSeparateGet()
        {
            return View("Manual");
        }

        [HttpPost]
        [ActionName("ModelBindingInSeparateModels")]
        public IActionResult ModelBindingSeparatePost(CalculatorViewModel model)
        {
            ViewBag.Result = ModelState.IsValid
                ? model.Calc()
                : "Invalid input";

            return View("Result");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WepApp2.2/Views/Calc/Index.cshtml
@{
    ViewBag.Title = "Home Page - Backend2";
}

<div class="text-center">
    <h1>Form parameters parsing demo</h1>
    <ul>
        <li><a asp-controller="Calc" asp-action="Manual">Manual parsing in single action</a></li>
        <li><a asp-controller="Calc" asp-action="ManualWithParsingSeparate">Manual parsing in separate action</a></li>
        <li><a asp-controller="Calc" asp-action="ModelBindingInParameters">Model binding (parameters)</a></li>
        <li><a asp-controller="Calc" asp-action="ModelBindingInSeparateModels">Model binding (separate model)</a></li>
    </ul>
</div>

WepApp2.2/Views/Calc/Manual.cshtml
@{ var action = ViewContext.RouteData.Values["Action"] as string;
   var controller = ViewContext.RouteData.Values["Controller"] as string;
    ViewBag.Title = $"{action} - Backend2"; 
}


<div>
    <h1>@action</h1>
    @using (Html.BeginForm(action, controller, FormMethod.Post))
    {
        <div>
            @Html.TextBox("x", "", new { type = "number" })
        </div>

        <div> 
            @Html.DropDownList("action", new SelectList(new[] { "+", "-", "*", "/" }))
        </div>

        <div>
            @Html.TextBox("y", "", new {type="number" })
        </div>

        <button type="submit">Submit</button>
    }
</div>

WepApp2.2/Views/Calc/Result.cshtml
@{ 
 ViewBag.Title = "Result - Backend2";
}
<h1>Result</h1>
@ViewBag.Result

WepApp2.2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <h2>Backend2</h2>
        <nav><a asp-controller="Calc" asp-action="Index">Home</a></nav>
    </header>

    <main>
        @RenderBody()
    </main>

    <footer>
            &copy; 2022 - Backend1
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>